apiVersion: v1
kind: Service

metadata:
  name: banking-app-service
  namespace: banking-dev

spec:
  type: {{ .Values.service.type }}

  selector:
    app: banking-app

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}